### ISSUE TITLE
请问如何在react hooks中写asyncData方法

### ISSUE THREAD

**Issue by mackxu** [hubcarl/egg-view-react-ssr#7]
react hooks 实例代码
```
function Index(props) {}
// 此处如何改造?
Index.asyncData = () => {}
```

看到被包裹成Page的reactClass 
`app.react.renderElement(reactClass, locals)`

**Comment by hubcarl** [comment]
@mackxu https://github.com/easy-team/egg-react-webpack-boilerplate/commit/3f33ba71c15d94df943458565b616465280d1001
